### PR TITLE
readme

### PR DESCRIPTION
**Pull request by CHBMB**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

### CODE REVIEW

**Comment by sparklyballs** [comment]
retest this please

**Comment by CHBMB** [comment]
Implemented the java memory thing.  Tested it and seems to be working.

**Comment by sparklyballs** [comment]
retest this please

**Comment by sparklyballs** [comment]
retest this please

**Comment by sparklyballs** [comment]
retest this please

**Pull request merged**
